api/urls.py
from django.urls import include, path
from rest_framework import routers
from api import views


router = routers.DefaultRouter()
router.register(r'users',views.UserViewSet)
router.register(r'products',views.ProductViewSet)


urlpatterns = [
    path('', include(router.urls))
]

myapp/urls.py
from django.urls import path, include
from myapp.views import index, products, product_details, add_product, update_product, delete_product, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDelete, cart_add, cart_view, cart_remove, order_summary, payment_success, order_history


app_name = 'myapp'

urlpatterns = [
    path('', index,name='index'),
    # path('products/', products, name='products'),
    path('products/', ProductListView.as_view(), name='products'),
    # path('products/<int:id>', product_details, name='product_details'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='product_details'),
    path('products/add', add_product, name='add_product'),
    # path('products/add', ProductCreateView.as_view(), name='add_product'),
    path('products/update/<int:id>', update_product, name='update_product'),
    # path('products/update/<int:pk>', ProductUpdateView.as_view(), name='update_product'),
    path('products/delete/<int:id>', delete_product, name='delete_product'),
    # path('products/delete/<int:pk>', ProductDelete.as_view(), name='delete_product'),
    path('cart_add/<int:id>', cart_add, name='cart_add'),
    path('cart_view', cart_view, name='cart_view'),
    path('cart_remove/<int:id>', cart_remove, name='cart_remove'),
    path('order_summary', order_summary, name='order_summary'),
    path('payment_success', payment_success, name='payment_success'),
    path('order_history', order_history, name='order_history'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

from myapp.views import index,products
from mysite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path('users/',include('users.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    
    
]

urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import register, profile, create_profile, seller_profile
from django.contrib.auth import views as authentication_views


app_name = 'users'


urlpatterns = [

    path('register/', register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name = 'login.html'), name = 'login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name = 'logout.html'), name = 'logout'),
    path('profile/', profile, name='profile'),
    path('create_profile/', create_profile, name='createprofile'),
    path('seller_profile/<int:id>', seller_profile, name='sellerprofile'),
    

]

myapp/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Product(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=100, unique=True)
    price = models.FloatField()
    description = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to='images')
    seller = models.ForeignKey(User, on_delete=models.CASCADE, default=9)



class Cart(models.Model):

    def __str__(self):
        return self.product_name

    product_id = models.IntegerField()
    product_name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    
    


class OrderHistory(models.Model):

    def __str__(self):
        return self.product_name

    product_id = models.IntegerField()
    product_name = models.CharField(max_length=100)
    quantity = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DeleteView, CreateView, UpdateView, DetailView
from django.urls import reverse_lazy
from .models import Product, Cart, OrderHistory
from users.models import Profile
# Create your views here.

def index(request):
    return render(request, 'index.html')






@login_required
def products(request):
    p = Product.objects.all()

    context = {'products':p}
    return render(request, 'products.html', context = context)


class ProductListView(ListView):
    model = Product
    template_name = 'products.html'
    context_object_name = 'products'



def product_details(request, id):
    p = Product.objects.get(id = id)
    context = {'p':p}
    return render(request, 'product_details.html', context = context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product_details.html'
    context_object_name = 'p'



@login_required
def add_product(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        image = request.FILES['upload']
        seller = request.user   

        p = Product(name=name, price=price, description=desc, image=image, seller=seller)
        p.save()

        return redirect('products')
    
    return render(request, 'add_product.html')


class ProductCreateView(CreateView):
    model = Product
    fields = ['name','price','description','image','seller']
    template_name = 'add_product.html'
    success_url = reverse_lazy('products')







def update_product(request,id):
    p = Product.objects.get(id = id)
    context = {'p':p}

    if request.method == 'POST':
        p.name = request.POST.get('name')
        p.price = request.POST.get('price')
        p.description = request.POST.get('desc')

        try:
            p.image = request.FILES['upload']
        except Exception as e:
            print(e)
            pass

        p.save()

        return redirect('products')
    
    return render(request, 'update_product.html', context = context)



class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name','price','description','image','seller']
    template_name = 'update_product.html'
    context_object_name = 'p'
    success_url = reverse_lazy('products')








def delete_product(request,id):
    p = Product.objects.get(id = id)
    context = {'p':p}

    if request.method == 'POST':
        p.delete()
        return redirect('products')
    
    return render(request, 'delete_product.html', context = context)


class ProductDelete(DeleteView):
    model = Product
    template_name = 'delete_product.html'
    context_object_name = 'p'
    success_url = reverse_lazy('products')






@login_required
def cart_view(request):
# To view the items in the cart

    current_user = request.user
# To get cart items of current user
    cart_items = Cart.objects.filter(user_id = current_user)
# To make a list of product class objects containing products in the cart of current user
    product_object_list = []
    for item in cart_items:
        product_object_list.append(Product.objects.get(id = item.product_id))
# To find the total cart items and update on profile table of current user
    total_cart_items = len(product_object_list)
    profile_object = Profile.objects.get(user_id = current_user)
    profile_object.total_cart_items = total_cart_items
    profile_object.save()

    context = {
        "products": product_object_list,
        }
# To find the input quantity by the current user for each item in the cart
    if request.method == "POST":
        for cart_item in cart_items:
            qty = request.POST.get(str(cart_item.product_id))
            c_obj = Cart.objects.get(product_id = cart_item.product_id, user_id = current_user)
            c_obj.quantity = qty
            c_obj.save()
            
        return redirect('order_summary')
    
    return render(request, 'cart_details.html', context=context)




@login_required
def cart_add(request, id):
# To add items to the cart table
    current_user = request.user
# To avoid adding of similar items in the cart
    cart_item = Cart.objects.filter(user_id = current_user)
    flag = True
    for item in cart_item:
        if int(item.product_id) != id:
            flag = True
        else:
            flag = False
            break

    if flag:        
        p = Product.objects.get(id = id)

        product_id = p.id
        product_name = p.name
        current_user = current_user

        c_add = Cart(product_id = product_id, product_name = product_name, user = current_user)
        c_add.save()

    return redirect('cart_view')






def cart_remove(request, id):
# To remove induvitual items from cart    
    current_user = request.user
    c = Cart.objects.filter(product_id = id, user_id = current_user)
    c.delete()

    return redirect('cart_view')




def order_summary(request):
# To view oder summary
    current_user = request.user

    cart_items = Cart.objects.filter(user_id = current_user)

    product_object_list = []
    for cart_item in cart_items:
        product_object_list.append(Product.objects.get(id = cart_item.product_id))
# To find total amount based on the quantity and price
    total_amount = 0
    for product_item in product_object_list:
        for cart_item in cart_items:
            if product_item.id == cart_item.product_id:
                total_amount = total_amount + (product_item.price * cart_item.quantity)

    context = {
        "products": product_object_list,
        "cart" : cart_items,
        "total_amount" : total_amount
        }

    return render(request, "order_summary.html", context=context)



def payment_success(request):
# To perfome after payment     
    current_user = request.user
    cart_items = Cart.objects.filter(user_id = current_user)
# To write odered items to oderhistory table
    for item in cart_items:
        oder_object = OrderHistory() 
        oder_object.product_id = item.product_id
        oder_object.product_name = item.product_name
        oder_object.user = current_user
        oder_object.quantity = item.quantity
        oder_object.save()
# after writing oderhistory table, deleteing all cart items of current user        
    cart_items.delete()

    profile_object = Profile.objects.get(user_id = current_user)
    profile_object.total_cart_items = 0
    profile_object.save()

    return render(request, "payment_success.html")




def order_history(request):
# To view orderd items of current user
    current_user = request.user
    oder_items = OrderHistory.objects.filter(user_id = current_user)

    product_object_list = []
    for item in oder_items:
        product_object_list.append(Product.objects.get(id = item.product_id))
    
    context = {
        "products" : product_object_list,
        "oder_items" : oder_items
        }

    return render(request, "order_history.html", context = context)

myapp/templates/add_product.html
{% extends 'base.html' %}
{% block content %}


<form style="position:relative; left: 450px; margin-top: 2%;" action="" method="POST" enctype="multipart/form-data" class='card-body w-2/6 shadow-2xl m-10 p-10'>
    {% csrf_token %}
    <h1 class="text-2xl font-bold mb-10 text-green-500" >➕ ADD Product</h1>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Name</label>
        <input class="input input-bordered w-full max-w-xs" type="text" name="name" id="name" placeholder="Name">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Price</label>
        <input class="input input-bordered w-full max-w-xs" type="text" name="price" id="price" placeholder="price">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Description</label>
        <input class="input input-bordered w-full max-w-xs" type="text" name="desc" id="desc" placeholder="Description">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product image</label>
        <input type="file" name="upload" id="upload">
    </div>
    <div >
        <input style="position:relative; left: 125px; margin-top: 3%;" class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg  px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800 w-2/5" type="submit" accept="image/*" name="Add Product" value="Add Product">
    </div>
</form>





{% endblock %}

myapp/templates/base.html
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en" data-theme="garden">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  {% tailwind_css %}
</head>

<body>
  
  <div class="navbar bg-blue-400 drop-shadow-md">
    <div class="flex-1">
      <a class="btn btn-ghost normal-case text-xl font-extrabold" href="{% url 'myapp:products' %}">MySite Cart</a>
    </div>
    <div class="flex-none">
      
      {% if user.is_authenticated %}
        <p>Hello {{user}}</p>
      {% endif %}
      
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-ghost btn-circle">
          <div class="indicator">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
              stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
            <span class="badge badge-sm indicator-item">{{user.profile.total_cart_items}}</span>
          </div>
        </label>
        <div tabindex="0" class="mt-3 card card-compact dropdown-content w-52 bg-base-100 shadow">
          <div class="card-body">
            <span class="font-bold text-lg">total items : {{user.profile.total_cart_items}}</span>
            <div class="card-actions">
              <a href="{% url 'myapp:cart_view' %}"><button class="btn btn-primary btn-block">View cart</button></a>
            </div>
          </div>
        </div>
      </div>
      <div class="dropdown dropdown-end z-70">
        <label tabindex="0" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full bg-slate-500">
            
       

          </div>
        </label>
        <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
          

          {% if user.is_authenticated %}
            <li><a href="{% url 'users:profile' %}">Profile 👩🏻‍💼</a></li>
            <li><a href="{% url 'users:logout' %}">Logout❕</a></li>
          {% else %}
            <li><a href="{% url 'users:login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </div>
  </div>

  {% block content %}



  
  {% endblock %}

</body>
</html>

myapp/templates/cart_details.html
{% extends 'base.html' %}
{% block content %}




<h1  class="m-4 text-purple-600 text-5xl font-extrabold text-center">CART ITEMS</h1>
<form action="" method="POST">
{% csrf_token %} 

<div class="mt-12">
   
{% for product in products %}
<div class="flex flex-col items-center bg-white border rounded-lg shadow-md md:flex-row w-3/6 m-6 ">
    <img class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="{{product.image.url}}" alt="">
    <div class="flex flex-col justify-between p-4 leading-normal w-full">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-black">{{product.name}}</h5>
    </div>
    <label class="font-semibold">Quantity:</label>
    <input class="h-8 w-14 p-1" type="number" name="{{product.id}}" min="1" max="15" value="1">
    <div class="flex flex-col justify-between p-4 leading-normal text-end w-full">
        <p class="font-bold text-black text-xl">₹{{product.price}}</p>
        <a href="{% url 'myapp:cart_remove' product.id %}" class="text-red-700 hover:text-white border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900 w-2/5 p-2 mx-12 mt-6">remove</a>
    </div>
</div>
{% endfor %}

</div>






<div class="flex justify-center">
    <div class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow-md dark:bg-white dark:border-white m-5">
        <h5 class="mb-5 text-2xl font-bold tracking-tight underline text-center">SUMMARY</h5>
        <p class="mb-2 font-bold text-lg">Total items : {{user.profile.total_cart_items}}</p>
        <input type="submit" class="text-white font-medium rounded-lg text-lg dark:bg-green-500 dark:hover:bg-green-600 p-2 ml-6 mt-4 mr-5" value="CHECK OUT">
    </div>
</div>

</form>



<div class="flex justify-center">
    <a href="{% url 'myapp:products' %}"><button class="text-white font-medium rounded-lg text-lg dark:bg-sky-500 dark:hover:bg-sky-600 p-2 mr-12 mt-4 mb-5 ml-12">Continue Shopping</button></a>
</div>



{% endblock %}

myapp/templates/delete_product.html
{% extends 'base.html' %}
{% block content %}



<form style="position:relative; left: 450px; margin-top: 2%;" action="" method="POST" enctype="multipart/form-data" class='card-body w-2/6 shadow-2xl m-10 p-10'>
    <h1 class="text-2xl font-bold mb-10 text-red-500" >🗑️Delete Product</h1>
    {% csrf_token %}
    <div class="mb-6 font-bold">
        <label for="">Product Name : {{p.name}}</label>
    </div>
    <div class="mb-6 font-bold">
        <label for="">Product Price : {{p.price}}</label>
    </div>
    <div class="mb-6 font-bold">
        <label for="">Product Description : {{p.description}}</label>
    </div>
    {% if p.image %}
        <div class="mb-6 font-bold">
            <label for="">Product Image</label>
            <img class="w-36 mb-2 rounded-lg" src="{{p.image.url}}" alt="image not found">
        </div>
    {% else %}
        <div class="mb-6 font-bold">
            <label for="">Product Image</label>
            <img class="w-36 mb-2 rounded-lg" src="" alt="Currently no image added">
        </div>
    {% endif %}
    <div >
        <input style="position:relative; left: 125px; margin-top: 3%;" class="text-red-700 hover:text-white border border-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg px-5 py-2.5 text-center mr-2 mb-2 dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900 w-2/5" type="submit" accept="image/*" name="Delete Product" value="Delete Product">
    </div>
</form>






{% endblock %}

myapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="color:rgb(0,0,0) ;">MY APP</h1>
    </body>
</html>

myapp/templates/oder_history.html
{% extends 'base.html' %}
{% block content %}




<h1  class="m-4 text-purple-600 text-5xl font-extrabold text-center">Order History</h1>

<div class="mt-12">
    
{% for product in products %}
<div class="flex flex-col items-center bg-white border rounded-lg shadow-md md:flex-row w-3/6 m-6 ">
    <img class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="{{product.image.url}}" alt="">
    <div class="flex flex-col justify-between p-4 leading-normal w-full">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-black">{{product.name}}</h5>
    </div>
    <div class="flex flex-col justify-between p-4 leading-normal text-end w-full">
        <p class="font-bold text-black text-xl">Ordered</p>
    </div>
</div>
{% endfor %}

</div>

<div class="flex justify-center">
    <a href="{% url 'myapp:products' %}"><button class="text-white font-medium rounded-lg text-lg dark:bg-sky-500 dark:hover:bg-sky-600 p-2 mr-12 mt-4 mb-5">Home</button></a>
</div>


{% endblock %}

myapp/templates/payment_success.html
{% extends 'base.html' %}
{% block content %}




<h1 class="m-4 mt-10 text-green-600 text-5xl font-extrabold text-center">Payement Success</h1>
<h1 class="m-4 mt-10 text-pink-600 text-4xl font-extrabold text-center">Thank You</h1>
<div class="flex justify-center">
<a href="{% url 'myapp:products' %}"><button class="text-white font-medium rounded-lg text-lg dark:bg-sky-500 dark:hover:bg-sky-600 p-2 ml-6 mt-4">Continue Shoping</button></a>
<a href="{% url 'myapp:oder_history' %}"><button class="text-white font-medium rounded-lg text-lg dark:bg-yellow-500 dark:hover:bg-yellow-600 p-2 ml-6 mt-4">View Oder History</button></a>
</div>







{% endblock %}

myapp/templates/product_details.html
{% extends 'base.html' %}
{% block content %}

    
<div class="flex flex-auto justify-center">
  <div class="card glass w-2/5 bg-base-100 shadow-2xl mt-7">
       {% if p.image %}
         <figure class="p-1">
           <img src="{{p.image.url}}" alt="Shoes" class="rounded-xl" />
         </figure>
       {% endif %}
       <div class="card-body items-center text-center ">
         <h2 class="card-title uppercase">{{p.name}}</h2>
         <p class="text-lg">{{p.description}}</p>
         <p class="text-2xl font-bold">₹{{p.price}}</p>
         <div class="card-actions">
           <a href="{% url 'myapp:cart_add' p.id %}"><button class="text-black underline font-medium rounded-lg text-lg dark:bg-amber-400 dark:hover:bg-amber-500 p-2 w-full">ADD TO CART</button></a>            
         </div>
         <p>Sold by : {{p.seller}}</p>
         <a href="{% url 'users:sellerprofile' p.seller.id %}"><div class="text-xl underline decoration-solid text-sky-900 hover:text-sky-500">Seller Details</div></a>
       </div>
     </div> 
</div>  




{% endblock %}

myapp/templates/products.html
{% extends 'base.html' %}
{% block content %}


{% comment %} <div class="flex flex-row justify-center"> {% endcomment %}
  <div class="grid grid-flow-row-dense grid-cols-2 gap-12 p-10">

    {% for p in products %}
    <div class="card w-96 glass m-10 shadow-2xl">
      {% if p.image %}
        <figure><img class="object-cover h-60 w-90" src="{{p.image.url}}" alt="not found!"/></figure>
      {% else %}
        <figure><img class="object-cover h-60 w-90" src="" alt="not found!"/></figure>
      {% endif %}
      <div class="card-body">
        <h2 class="card-title uppercase">{{p.name}}</h2>
        <p>{{p.description}}</p>
        <div class="card-actions justify-end">
          <a href="{% url 'myapp:product_details' p.id %}">
          <button class="btn btn-primary bg-blue-800">₹{{p.price}}</button>
          </a>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
</div>
   

{% endblock %}

myapp/templates/update_product.html
{% extends 'base.html' %}
{% block content %}




<form style="position:relative; left: 450px; margin-top: 2%;" action="" method="POST" enctype="multipart/form-data" class='card-body w-2/6 shadow-2xl m-10 p-10'>
    {% csrf_token %}
    <h1 class="text-2xl font-bold mb-10 text-yellow-500" >✏️ Update Product</h1>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Name</label>
        <input class="input input-bordered w-full max-w-xs" type="text" name="name" id="name" value="{{p.name}}" placeholder="Name">
    </div>

    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Price</label>
        <input class="input input-bordered w-full max-w-xs" type="text" name="price" id="price" value="{{p.price}}" placeholder="price" >
    </div>

    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Description</label>
        <input class="input input-bordered w-full max-w-xs" type="text" name="desc" id="desc" value="{{p.description}}" placeholder="Description">
    </div>

    {% if p.image %}
        <div class="mb-5">
            <label class="block text-grey-700 text-sm font-bold mb-2">Product image</label>
            <img class="w-36 mb-2 rounded-lg" src="{{p.image.url}}" alt="image not found">
            <input type="file" name="upload" id="upload">
        </div>
    {% else %}
    <div class="mb-6">
        <label for="">Product Image</label>
        <img class="w-36 mb-2 rounded-lg" src="" alt="Currently no image added">
        <input type="file" name="upload" id="upload">
    </div>
    {% endif %}  
         
    <div >
        <input style="position:relative; left: 125px; margin-top: 3%;" class="focus:outline-none text-white bg-yellow-500 hover:bg-yellow-600 focus:ring-4 focus:ring-yellow-300 font-medium rounded-lg px-5 py-2.5 mr-2 mb-2 dark:focus:ring-yellow-900 w-2/5" type="submit" accept="image/*" name="Update Product" value="Update Product">
    </div>
</form>



{% endblock %}